# NB: don't set `language: haskell` here
# See https://github.com/hvr/multi-ghc-travis for more information

env:
 - GHCVER=6.12.3
# - GHCVER=7.0.1  # disabled due to internal GHC failure
 - GHCVER=7.0.2
 - GHCVER=7.0.3
 - GHCVER=7.0.4
 - GHCVER=7.2.1
 - GHCVER=7.2.2
 - GHCVER=7.4.1
 - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3
 - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
# can't use "cabal install --only-dependencies --enable-tests" due to dep-cycle
 - cabal-1.18 install "QuickCheck >=2.4 && <2.7" "byteorder ==1.0.*" "dlist ==0.5.*" "mtl >=2.0 && <2.2" deepseq

script:
 - cabal-1.18 configure --enable-tests -v2
 - cabal-1.18 build
 - cabal-1.18 test
# "cabal check" disabled due to -O2 warning
# - cabal-1.18 check
 - cabal-1.18 sdist
